export const doctors = [
    ["Dr. Sirikonda Aishwarya", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. B. Kiran", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Alavala Sri Lakshmi", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Y. Yamini", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Bandi Sai Manikanta", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. B. Ratnakar", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Banoth Yaswanth", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. L. Kiran Kumar", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Boddu Nageshwararao", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Ranjith Kumar", "Ophthalmology", "Government General Hospital Khammam"],
    ["Dr. Guguloth Bhav Singh", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. E. Sowjanya", "ENT", "Government General Hospital Khammam"],
    ["Dr. K Sunil Kumar", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. J. Tulasi", "Dermatology & STD", "Government General Hospital Khammam"],
    ["Dr. Kandula Abhilash Reddy", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Sowmya", "Psychiatry", "Government General Hospital Khammam"],
    ["Dr. Nallani Niveditha", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Thabitha Rani", "Dental", "Government General Hospital Khammam"],
    ["Dr. Naragani Ram Prasad", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. V. Seetharam", "Cardiology", "Government General Hospital Khammam"],
    ["Dr. Narreddy Hitesh Jayarami Reddy", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Mounika", "Pulmonology", "Government General Hospital Khammam"],
    ["Dr. Niaz Farhat", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Pedamalla Sravanthi", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Ponnam Bala Ramakrishna", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Prasanthi Katragadda", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Rajeev Kumar Togiti", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Ravvala Tejaswi", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Shama Firdaus", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Solthi Sunil", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Syed Zia Hussain", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Vasireddy Benarjee", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Yerakala Ramesh", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Afiya Tabassum", "Dental", "Government General Hospital Khammam"],
    ["Dr. B Lavanya", "Dental", "Government General Hospital Khammam"],
    ["Dr. Lakavath Rambabu", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. M Likhita", "Cardiology", "Government General Hospital Khammam"],
    ["Dr. Badikala Prathyusha", "Dermatology & STD", "Government General Hospital Khammam"],
    ["Dr. Nallamotu Vyshnavi", "Dermatology & STD", "Government General Hospital Khammam"],
    ["Dr. Pasumarthi Keerthi Pravallika", "Dermatology & STD", "Government General Hospital Khammam"],
    ["Dr. Tulasi Jarang", "Dermatology & STD", "Government General Hospital Khammam"],
    ["Dr. Embadi Soujanya", "ENT", "Government General Hospital Khammam"],
    ["Dr. Gunnam Bindhu Sravanthi", "ENT", "Government General Hospital Khammam"],
    ["Dr. Hajira Siddiqua", "ENT", "Government General Hospital Khammam"],
    ["Dr. Mada Roja", "ENT", "Government General Hospital Khammam"],
    ["Dr. Ajmal Ahmed", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Anapana Yamuna", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Inturi Pranay", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Jagarlamudi Anil Babu", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Kiran Kumar Bollepaka", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Manthena Manohar", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Pawan Kumar Hosamani", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Anuganti Sahithi", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Banoth Parvathi", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Byru Srividya", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Kalapala Madhavi", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Musuku Radhika", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Peravali Yamini Shoba Vani", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Dharavathu Ramu Nayak", "Ophthalmology", "Government General Hospital Khammam"],
    ["Dr. Keith Raveena Reddy", "Ophthalmology", "Government General Hospital Khammam"],
    ["Dr. Mareddy Sriram", "Ophthalmology", "Government General Hospital Khammam"],
    ["Dr. Pasupuleti Mahesh", "Ophthalmology", "Government General Hospital Khammam"],
    ["Dr. Shaik Asma", "Ophthalmology", "Government General Hospital Khammam"],
    ["Dr. Busetty Mallik Chandrasekhar", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Chennupati Vinay Kumar", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Cherukuri Meghana", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Meka Naga Kiran", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Rajesh Kolipaka", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Tejavath Madan Singh", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Bunga Babu Ratnakar", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Chippalapally Rambabu", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Natta Monica", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Paladi Sree Gnyana Vallabha", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Bandela Sowmya Grace", "Psychiatry", "Government General Hospital Khammam"],
    ["Dr. Kavuloori Sai Rithish Bharadwaj", "Psychiatry", "Government General Hospital Khammam"],
    ["Dr. Gundla Sunitha", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Manne Haripriya", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Nandru Shilpa", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Thangellapalli Sai Bhargav", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Yellamelli Prathyusha", "Paediatrics", "Government General Hospital Khammam"],
    ["Dr. Kondapally Sreemouni", "Dermatology & STD", "Government General Hospital Khammam"],
    ["Dr. Pavani Kusuma", "Dermatology & STD", "Government General Hospital Khammam"],
    ["Dr. Amradi Sahruda", "ENT", "Government General Hospital Khammam"],
    ["Dr. Gopagani Surender", "Pulmonology", "Government General Hospital Khammam"],
    ["Dr. K N Sree Sai Gayathri", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Kanakapudi Keerthi Kumar", "General Medicine", "Government General Hospital Khammam"],
    ["Dr. Anitha Vallapatla M", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Karimilla Reethika", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Karthan Sri Latha", "General Surgery", "Government General Hospital Khammam"],
    ["Dr. Ganduri Aparna", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Kasimkuppam Divyasree", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. N Akshara Jyothi", "Obstetrics & Gynaecology", "Government General Hospital Khammam"],
    ["Dr. Nalini Jayanthi Ravilala", "Ophthalmology", "Government General Hospital Khammam"],
    ["Dr. Dholavan Hanuman Singh", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Lakavat Kiran Kumar", "Orthopaedics", "Government General Hospital Khammam"],
    ["Dr. Mohammed Irfan", "Pulmonology", "Government General Hospital Khammam"],
    ["Dr. Krishna Kishore", "Cardiology", "KHIMS Hospitals"],
    ["Dr. Ravindranath Chaudhary Mallampati", "Orthopaedics", "KHIMS Hospitals"],
    ["Dr. Peddireddy Sudhindra Reddy", "Neuro & Spine Surgery", "KHIMS Hospitals"],
    ["Dr. M Vinod Babu", "Nephrology", "KHIMS Hospitals"],
    ["Dr. Sareen Reddy Seelam", "Oral & Maxillofacial Surgery", "KHIMS Hospitals"],
    ["Dr. Rakesh Challagulla", "Paediatrics", "Ankura Hospital"],
    ["Dr. Kalpana", "General Physician", "Ankura Hospital"],
    ["Dr. Sweta Yudhistir", "Paediatrics", "Ankura Hospital"],
    ["Dr. Sai Prasanna", "Gynaecology", "Ankura Hospital"],
    ["Dr. MD Jakeer Shaikh", "Paediatrics", "Ankura Hospital"],
    ["Dr. Y Aparna Laxmi", "Paediatrics", "Ankura Hospital"],
    ["Dr. Sindu Bandla", "Paediatrics", "Ankura Hospital"],
    ["Dr. Jyoshna", "Gynaecology", "Ankura Hospital"],
    ["Dr. Andhra Jyothi", "General Physician", "Ankura Hospital"],
    ["Dr. Shaik Huma", "Paediatrics", "Ankura Hospital"],
    ["Dr. Praveen Kumar A", "Cardiology", "Akshara Cardiac Hospital"],
    ["Dr. Arif Mohammad", "Orthopaedics", "Prashanthi Hospital"],
    ["Dr. Hemanth", "General Surgery", "Ushodaya Hospital"],
    ["Dr. Kavyachand Yalamudi", "General Physician", "Newlife Hospitals"],
    ["Dr. P Sindhu", "Gynaecology", "Sarojini Hospital"],
    ["Dr. Bhaskar Reddy", "Paediatrics", "Sarojini Hospital"],
    ["Dr. V Naresh", "Dentistry", "Sai Denti Nova Super Speciality Dental Hospital"],
    ["Dr. Charagundla Rajasekhar Ayyappa", "General Physician", "Sravanthi Hospital"],
    ["Dr. Hanuman", "Orthopaedics", "Hanuman Orthopaedic Hospital"]
];

export const hospitals = [
    ["Government General Hospital Khammam", "Tertiary Government Hospital", "Wyra Road, Khammam, Telangana 507002", "https://www.google.com/maps/search/?api=1&query=Government+General+Hospital+Khammam"],
    ["KHIMS Hospitals", "Super Speciality Hospital", "Vaira Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=KHIMS+Hospitals+Khammam"],
    ["Ankura Hospital", "Multi-speciality Hospital", "Khanapuram Haweli, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Ankura+Hospital+Khammam"],
    ["Akshara Cardiac Hospital", "Cardiology Hospital", "Venkatagiri, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Akshara+Cardiac+Hospital+Khammam"],
    ["Prashanthi Hospital", "Multi-speciality Hospital", "Nehru Nagar, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Prashanthi+Hospital+Khammam"],
    ["Ushodaya Hospital", "Hospital", "Khammampadu, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Ushodaya+Hospital+Khammam"],
    ["Newlife Hospitals", "Multi-speciality Hospital", "Bus Station area, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Newlife+Hospitals+Khammam"],
    ["Sarojini Hospital", "Multi-speciality Hospital", "Rotary Nagar, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sarojini+Hospital+Khammam"],
    ["Sai Denti Nova Super Speciality Dental Hospital", "Dental Hospital", "Balaji Nagar, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sai+Denti+Nova+Khammam"],
    ["Sravanthi Hospital", "Internal Medicine Hospital", "Kothagudem Colls, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sravanthi+Hospital+Khammam"],
    ["Hanuman Orthopaedic Hospital", "Orthopaedic Hospital", "Balaji Nagar, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Hanuman+Orthopaedic+Hospital+Khammam"],
    ["Sree Venkateswara Hospital", "Multi-speciality Hospital", "Sathupalli Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sree+Venkateswara+Hospital+Khammam"],
    ["Viveka Hospital", "Super Speciality Hospital", "Main Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Viveka+Hospital+Khammam"],
    ["Krishna Hospital", "Multi-speciality Hospital", "Madhira Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Krishna+Hospital+Khammam"],
    ["Sree Sai Hospital", "General Hospital", "Kallur, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sree+Sai+Hospital+Khammam"],
    ["Mother Teresa Hospital", "Multi-speciality Hospital", "Kothagudem Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Mother+Teresa+Hospital+Khammam"],
    ["Raghavendra Hospital", "General Hospital", "Station Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Raghavendra+Hospital+Khammam"],
    ["Sri Sai Ram Hospital", "Multi-speciality Hospital", "Madhav Nagar, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sri+Sai+Ram+Hospital+Khammam"],
    ["Yashoda Hospital Khammam", "Multi-speciality Hospital", "Central Bus Stand Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Yashoda+Hospital+Khammam"],
    ["Medicover Hospital Khammam", "Multi-speciality Hospital", "Srinivasa Colony, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Medicover+Hospital+Khammam"],
    ["Sushma Hospital", "Multi-speciality Hospital", "Beside RTC Complex, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sushma+Hospital+Khammam"],
    ["Nirmala Hospital", "General Hospital", "Ammugudem, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Nirmala+Hospital+Khammam"],
    ["Jeevani Hospital", "Super Speciality Hospital", "Mahadevpuram, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Jeevani+Hospital+Khammam"],
    ["Shivam Hospital", "General Hospital", "Madhira Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Shivam+Hospital+Khammam"],
    ["Sree Hospitals", "Multi-speciality Hospital", "Veterinary Hospital Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sree+Hospitals+Khammam"],
    ["Gouthami Hospital", "Maternity Hospital", "Banjara Hills Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Gouthami+Hospital+Khammam"],
    ["Sunrise Hospital", "Multi-speciality Hospital", "Kothagudem Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sunrise+Hospital+Khammam"],
    ["Sai Krishna Hospital", "Multi-speciality Hospital", "Madhira Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Sai+Krishna+Hospital+Khammam"],
    ["Maheshwari Hospital", "General Hospital", "Ashok Nagar, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Maheshwari+Hospital+Khammam"],
    ["Vasanth Hospital", "Multi-speciality Hospital", "Nirmal Nagar, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Vasanth+Hospital+Khammam"],
    ["Vision Eye Hospital", "Eye Hospital", "Madhira Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Vision+Eye+Hospital+Khammam"],
    ["Arogya Hospital", "Multi-speciality Hospital", "Kusumanchi Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Arogya+Hospital+Khammam"],
    ["Life Line Hospital", "General Hospital", "Near Collectorate, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Life+Line+Hospital+Khammam"],
    ["Dr. Arogya Hospital", "General Hospital", "Ramalayam Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Dr+Arogya+Hospital+Khammam"],
    ["Khammam Care Hospital", "Multi-speciality Hospital", "Main Road, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Khammam+Care+Hospital"],
    ["Mahalakshmi Hospital", "Multi-speciality Hospital", "Sanjay Nagar, Khammam, Telangana", "https://www.google.com/maps/search/?api=1&query=Mahalakshmi+Hospital+Khammam"]
];